// GENERATED by tests/make-manifest.js - do not edit by hand.
// 345 files, 226 runnable in the automated diff.
var MANIFEST = [
 {
  "path": "debugging/debug-01",
  "lines": 6,
  "tags": [
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-02",
  "lines": 6,
  "tags": [
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-03",
  "lines": 9,
  "tags": [
   "classroom",
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-04",
  "lines": 7,
  "tags": [
   "interactive",
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-05",
  "lines": 15,
  "tags": [
   "interactive",
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-06",
  "lines": 19,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "debugging/debug-07",
  "lines": 61,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "expect-error"
  ],
  "auto": true
 },
 {
  "path": "demos/bit_game",
  "lines": 2709,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "demos/card_prediction",
  "lines": 36,
  "tags": [
   "hardware",
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/chocolates",
  "lines": 50,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "demos/dance",
  "lines": 310,
  "tags": [
   "network",
   "hardware",
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "demos/endless_runner",
  "lines": 131,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/escape",
  "lines": 1923,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "demos/fashion",
  "lines": 138,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "demos/first_aid",
  "lines": 94,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "demos/gamedemo1",
  "lines": 37,
  "tags": [
   "network",
   "widgets",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "demos/landing_game",
  "lines": 92,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/multi_microbits",
  "lines": 16,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/ninetrick",
  "lines": 89,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "demos/pong",
  "lines": 263,
  "tags": [
   "network",
   "hardware",
   "canvas",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/pyracer",
  "lines": 224,
  "tags": [
   "network",
   "canvas",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/snake",
  "lines": 141,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "demos/threecolumn",
  "lines": 77,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "demos/tictactoe",
  "lines": 245,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/tictactoe_ml",
  "lines": 253,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/tournament",
  "lines": 2076,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "demos/turtle",
  "lines": 5,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/turtle_demo",
  "lines": 80,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 },
 {
  "path": "demos/turtle_reference",
  "lines": 40,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 },
 {
  "path": "demos/turtle_starter",
  "lines": 2,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/vr",
  "lines": 37,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "demos/vr2",
  "lines": 92,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "example",
  "lines": 18,
  "tags": [
   "nondeterministic",
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "inquisitive/jamiegame",
  "lines": 168,
  "tags": [
   "network",
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/jamiegame_buggy",
  "lines": 156,
  "tags": [
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/password",
  "lines": 45,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "inquisitive/playerSelection",
  "lines": 25,
  "tags": [
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/powerup",
  "lines": 176,
  "tags": [
   "network",
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l1starter",
  "lines": 3,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l2d1",
  "lines": 6,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l2q1",
  "lines": 2,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l2q2",
  "lines": 14,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l2q3",
  "lines": 23,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l2q5",
  "lines": 26,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l3d1",
  "lines": 102,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l3q7",
  "lines": 3,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "inquisitive/turtle/y5l3q8",
  "lines": 5,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 },
 {
  "path": "intermediate/0101e",
  "lines": 32,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0102e",
  "lines": 17,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0103e",
  "lines": 12,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0201e",
  "lines": 11,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0202e",
  "lines": 11,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0203e",
  "lines": 19,
  "tags": [
   "interactive",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0204e",
  "lines": 29,
  "tags": [
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0301e",
  "lines": 24,
  "tags": [
   "nondeterministic",
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0302e",
  "lines": 16,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0303e",
  "lines": 9,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0401e",
  "lines": 12,
  "tags": [
   "nondeterministic",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0402e",
  "lines": 12,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0403e",
  "lines": 49,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0501e",
  "lines": 20,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0502e",
  "lines": 21,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0503e",
  "lines": 1,
  "tags": [
   "nondeterministic"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0601e",
  "lines": 11,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0602e",
  "lines": 9,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/0603e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "intermediate/0701e",
  "lines": 3,
  "tags": [],
  "auto": true
 },
 {
  "path": "intermediate/answers/0101a",
  "lines": 33,
  "tags": [],
  "auto": true
 },
 {
  "path": "intermediate/answers/0102a",
  "lines": 17,
  "tags": [],
  "auto": true
 },
 {
  "path": "intermediate/answers/0103a",
  "lines": 12,
  "tags": [],
  "auto": true
 },
 {
  "path": "intermediate/answers/0201a",
  "lines": 11,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0202a",
  "lines": 11,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0203a",
  "lines": 23,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0204a",
  "lines": 30,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0301a",
  "lines": 24,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0302a",
  "lines": 16,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0303a",
  "lines": 13,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0401a",
  "lines": 9,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0402a",
  "lines": 12,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0403a",
  "lines": 49,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0501a",
  "lines": 20,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0502a",
  "lines": 21,
  "tags": [
   "nondeterministic",
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0503a",
  "lines": 20,
  "tags": [
   "nondeterministic",
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0601a",
  "lines": 11,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0602a",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0603a",
  "lines": 14,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0701a",
  "lines": 98,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/answers/0702a",
  "lines": 158,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0201d",
  "lines": 27,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0202d",
  "lines": 40,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0301d",
  "lines": 33,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0401d",
  "lines": 10,
  "tags": [
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0402d",
  "lines": 12,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0403d",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0501d",
  "lines": 20,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0502d",
  "lines": 19,
  "tags": [
   "nondeterministic",
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0601d",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0602d",
  "lines": 11,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0603d",
  "lines": 11,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0701d",
  "lines": 99,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intermediate/demos/0702d",
  "lines": 159,
  "tags": [
   "nondeterministic",
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0101e",
  "lines": 705,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0102e",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0103e",
  "lines": 2,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0104e",
  "lines": 2,
  "tags": [
   "speech"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/0105e",
  "lines": 99,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/0201e",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0202e",
  "lines": 5,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0203e",
  "lines": 3,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0204e",
  "lines": 5,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0205e",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0206e",
  "lines": 90,
  "tags": [
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0301e",
  "lines": 6,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0302e",
  "lines": 14,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0303e",
  "lines": 10,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0304e",
  "lines": 28,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0305e",
  "lines": 5,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/03501e",
  "lines": 5,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/03502e",
  "lines": 8,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0401e",
  "lines": 4,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0402_2e",
  "lines": 9,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0402e",
  "lines": 6,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0403e",
  "lines": 12,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0404e",
  "lines": 42,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/0501e",
  "lines": 7,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0502e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0503e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0504e",
  "lines": 48,
  "tags": [
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/0601e",
  "lines": 9,
  "tags": [
   "interactive",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0602e",
  "lines": 12,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0603e",
  "lines": 19,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0604e",
  "lines": 16,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/0605e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/0606e",
  "lines": 29,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/0701e",
  "lines": 62,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0101a",
  "lines": 289,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0102a",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0103a",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0104a",
  "lines": 4,
  "tags": [
   "speech"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/answers/0202a",
  "lines": 16,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0203a",
  "lines": 3,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0204a",
  "lines": 5,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0205a",
  "lines": 13,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0301a",
  "lines": 15,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0302a",
  "lines": 15,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0303a",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0305a",
  "lines": 28,
  "tags": [],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0401a",
  "lines": 4,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0402_2e",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0402a",
  "lines": 6,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0403a",
  "lines": 25,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0501a",
  "lines": 8,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0502a",
  "lines": 7,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0503a",
  "lines": 9,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0601a",
  "lines": 10,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0602a",
  "lines": 6,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0603a",
  "lines": 16,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0604a",
  "lines": 16,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/answers/0605a",
  "lines": 32,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0201d",
  "lines": 24,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "intro.v2/demos/0301d",
  "lines": 24,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/03501d",
  "lines": 91,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/03502d",
  "lines": 237,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/03503d",
  "lines": 36,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0401d",
  "lines": 10,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0402d",
  "lines": 3,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0501d",
  "lines": 28,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0502d",
  "lines": 3,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0601d",
  "lines": 14,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0602d",
  "lines": 199,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0603d",
  "lines": 7,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0701d",
  "lines": 289,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0702d",
  "lines": 309,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0703d",
  "lines": 442,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0704d",
  "lines": 101,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/demos/0705d",
  "lines": 167,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/guessASCII/puffer",
  "lines": 36,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/guessASCII/rhino",
  "lines": 32,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "intro.v2/guessASCII/rudolph",
  "lines": 22,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0101e",
  "lines": 274,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0102e",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "introduction/0103e",
  "lines": 3,
  "tags": [],
  "auto": true
 },
 {
  "path": "introduction/0104e",
  "lines": 99,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "introduction/0201e",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "introduction/0202e",
  "lines": 28,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0203e",
  "lines": 17,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/0204e",
  "lines": 90,
  "tags": [
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/0301e",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/0302e",
  "lines": 24,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/0303e",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/0304e",
  "lines": 28,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0401e",
  "lines": 8,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0402_2e",
  "lines": 9,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0402e",
  "lines": 9,
  "tags": [
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0403e",
  "lines": 12,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/0404e",
  "lines": 42,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "introduction/0501e",
  "lines": 12,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0502e",
  "lines": 12,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0503e",
  "lines": 5,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/0504e",
  "lines": 48,
  "tags": [
   "canvas",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "introduction/0601e",
  "lines": 14,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0602e",
  "lines": 34,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/0603e",
  "lines": 7,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/0604e",
  "lines": 29,
  "tags": [
   "canvas",
   "nondeterministic",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "introduction/0701e",
  "lines": 62,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0101a",
  "lines": 289,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0102a",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "introduction/answers/0103a",
  "lines": 4,
  "tags": [],
  "auto": true
 },
 {
  "path": "introduction/answers/0202a",
  "lines": 34,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0203a",
  "lines": 21,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0301a",
  "lines": 15,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0302a",
  "lines": 24,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0303a",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0401a",
  "lines": 8,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0402_2e",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0402a",
  "lines": 9,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0403a",
  "lines": 21,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0501a",
  "lines": 12,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0502a",
  "lines": 12,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0503a",
  "lines": 14,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0601a",
  "lines": 14,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0602a",
  "lines": 35,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/answers/0603a",
  "lines": 37,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0201d",
  "lines": 21,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0301d",
  "lines": 24,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/03501d",
  "lines": 91,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/03502d",
  "lines": 237,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/03503d",
  "lines": 36,
  "tags": [
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0401d",
  "lines": 10,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0501d",
  "lines": 25,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0601d",
  "lines": 14,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0701d",
  "lines": 289,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0702d",
  "lines": 308,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/demos/0703d",
  "lines": 442,
  "tags": [
   "interactive",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/guessASCII/puffer",
  "lines": 36,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "introduction/guessASCII/rhino",
  "lines": 32,
  "tags": [
   "interactive",
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "introduction/guessASCII/rudolph",
  "lines": 22,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0101e",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0102d",
  "lines": 4,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0102e",
  "lines": 7,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0103d",
  "lines": 5,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0103e",
  "lines": 8,
  "tags": [
   "hardware",
   "speech",
   "interactive",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0201d",
  "lines": 23,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0201e",
  "lines": 24,
  "tags": [
   "nondeterministic",
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0202d",
  "lines": 18,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0202e",
  "lines": 16,
  "tags": [
   "interactive",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0203e",
  "lines": 3,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0204e",
  "lines": 3,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0301d",
  "lines": 28,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0301e",
  "lines": 2,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0302e",
  "lines": 2,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0303e",
  "lines": 25,
  "tags": [
   "network",
   "interactive",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0401d",
  "lines": 58,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0401e",
  "lines": 7,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0402e",
  "lines": 7,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0501d",
  "lines": 28,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0501e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0502e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0503e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0601d",
  "lines": 67,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/0601e",
  "lines": 39,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/0602e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0603e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0604e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/0701e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0101e",
  "lines": 11,
  "tags": [
   "speech",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0102e",
  "lines": 8,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0103e",
  "lines": 8,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0201e",
  "lines": 24,
  "tags": [
   "nondeterministic",
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0202d",
  "lines": 18,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0202e",
  "lines": 16,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0203e",
  "lines": 27,
  "tags": [
   "network",
   "nondeterministic",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0204e",
  "lines": 23,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0301d",
  "lines": 36,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0301e",
  "lines": 17,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0302e",
  "lines": 22,
  "tags": [
   "interactive"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0303e",
  "lines": 29,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0401e",
  "lines": 41,
  "tags": [
   "network",
   "interactive",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0402e",
  "lines": 45,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0501e",
  "lines": 23,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0502e",
  "lines": 31,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0503e",
  "lines": 41,
  "tags": [
   "interactive",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0601e",
  "lines": 51,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0602e",
  "lines": 59,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0603e",
  "lines": 63,
  "tags": [
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": true
 },
 {
  "path": "learntocode2/answers/0604e",
  "lines": 62,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/answers/0701e",
  "lines": 1,
  "tags": [],
  "auto": true
 },
 {
  "path": "learntocode2/imagesettest",
  "lines": 62,
  "tags": [
   "network",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "learntocode2/pytris",
  "lines": 425,
  "tags": [
   "network",
   "canvas",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "main",
  "lines": 3,
  "tags": [],
  "auto": true
 },
 {
  "path": "pythonai/0101d",
  "lines": 6,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0103d",
  "lines": 4,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0104e",
  "lines": 11,
  "tags": [
   "classroom"
  ],
  "auto": true
 },
 {
  "path": "pythonai/0105e",
  "lines": 7,
  "tags": [
   "interactive",
   "classroom",
   "blanks"
  ],
  "auto": true
 },
 {
  "path": "pythonai/0201d",
  "lines": 13,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0301d",
  "lines": 7,
  "tags": [
   "network",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0302d",
  "lines": 7,
  "tags": [
   "network",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0401d",
  "lines": 7,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0501d",
  "lines": 9,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/0601d",
  "lines": 11,
  "tags": [
   "network",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/answers/0104e",
  "lines": 11,
  "tags": [
   "speech",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "pythonai/answers/0105e",
  "lines": 8,
  "tags": [
   "speech",
   "interactive",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0101d",
  "lines": 8,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0101e",
  "lines": 8,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0102d",
  "lines": 60,
  "tags": [
   "hardware",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0102e",
  "lines": 8,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0103e",
  "lines": 22,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0104e",
  "lines": 28,
  "tags": [
   "hardware",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0201d",
  "lines": 14,
  "tags": [
   "hardware",
   "speech",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0201e",
  "lines": 12,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0202e",
  "lines": 14,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0203e",
  "lines": 13,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0204e",
  "lines": 20,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0301d",
  "lines": 22,
  "tags": [
   "hardware",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0301e",
  "lines": 21,
  "tags": [
   "hardware",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0302d",
  "lines": 17,
  "tags": [
   "hardware",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0302e",
  "lines": 20,
  "tags": [
   "hardware",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0303d",
  "lines": 21,
  "tags": [
   "hardware",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0303e",
  "lines": 17,
  "tags": [
   "hardware",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0304e",
  "lines": 21,
  "tags": [
   "hardware",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0401d",
  "lines": 35,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0401e",
  "lines": 33,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0402e",
  "lines": 34,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0403e",
  "lines": 31,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "goto",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0501d",
  "lines": 17,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0501e",
  "lines": 17,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0502d",
  "lines": 30,
  "tags": [
   "hardware",
   "speech",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0502e",
  "lines": 16,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0503e",
  "lines": 30,
  "tags": [
   "hardware",
   "speech",
   "nondeterministic",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0504e",
  "lines": 20,
  "tags": [
   "hardware",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/0601d",
  "lines": 25,
  "tags": [
   "hardware",
   "speech",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0601e",
  "lines": 24,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0602d",
  "lines": 20,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0602e",
  "lines": 23,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0603e",
  "lines": 23,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0604e",
  "lines": 22,
  "tags": [
   "hardware",
   "speech",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0701d",
  "lines": 36,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/0701e",
  "lines": 6,
  "tags": [
   "hardware",
   "classroom",
   "blanks"
  ],
  "auto": false
 },
 {
  "path": "robotics/0702d",
  "lines": 38,
  "tags": [
   "hardware",
   "speech",
   "nondeterministic",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/checkButtonAandBDemo",
  "lines": 23,
  "tags": [
   "hardware",
   "speech",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "robotics/test",
  "lines": 37,
  "tags": [
   "hardware",
   "nondeterministic",
   "interactive",
   "classroom",
   "goto"
  ],
  "auto": false
 },
 {
  "path": "robotics/testingListen",
  "lines": 17,
  "tags": [
   "hardware",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "turtle/001",
  "lines": 10,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "turtle/002",
  "lines": 14,
  "tags": [
   "canvas",
   "classroom"
  ],
  "auto": false
 },
 {
  "path": "turtle/003",
  "lines": 6,
  "tags": [
   "canvas",
   "classroom",
   "wheels"
  ],
  "auto": false
 }
];
